template = 'another_template'

title = 'Put some text here'

keywords = 'some,relevant,keywords'

content_md = '''
## Sample page with image

Look at that beautiful image...

![DSSG logo](../img/dssg-logo.jpg)
'''