template = 'another_template'

title = 'Put some text here'

keywords = 'some,relevant,keywords'

content_md = '''
## Sample page with links

How to insert links:

* [Homepage](../index.html "Homepage")
* [Sample Page 2](sample_page_2.html "Sample Page 2")
'''